# Generated by Django 5.1.7 on 2025-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comentariopost_created_at_comentariopost_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservico',
            name='conteudo',
            field=models.ImageField(blank=True, null=True, upload_to='midia/'),
        ),
    ]
