# Generated by Django 5.1.7 on 2025-04-02 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comentariopost_curtidas_postservico_curtidas_and_more'),
        ('profissionais', '0016_alter_profissional_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariopost',
            name='profissional',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional'),
            preserve_default=False,
        ),
    ]
