# Generated by Django 5.1.7 on 2025-04-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postservico_datacriacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentariopost',
            old_name='Post',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='comentariopost',
            name='dataCriacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
