# Generated by Django 5.1.7 on 2025-04-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_post_comentariopost_post_and_more'),
        ('profissionais', '0016_alter_profissional_numero'),
        ('servicos', '0006_alter_servico_descricao_alter_servico_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservico',
            name='idServico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.servico'),
        ),
        migrations.AlterField(
            model_name='postservico',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional'),
        ),
    ]
