# Generated by Django 5.1.7 on 2025-04-06 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_postservico_idservico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postservico'),
        ),
    ]
