# Generated by Django 5.1.7 on 2025-04-06 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_comentariopost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopost',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.postservico'),
        ),
    ]
