# Generated by Django 5.1.7 on 2025-04-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_comentariopost_post'),
        ('profissionais', '0016_alter_profissional_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopost',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional'),
        ),
    ]
