# Generated by Django 5.1.7 on 2025-05-05 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_comentariopost_curtidas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtida',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_post', to='posts.postservico'),
        ),
        migrations.AlterField(
            model_name='curtida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
