# Generated by Django 5.1.7 on 2025-03-08 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_servicos', to='clientes.cliente')),
                ('idProfissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissional_servicos', to='profissionais.profissional')),
            ],
        ),
    ]
