# Generated by Django 5.1.7 on 2025-04-02 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0016_alter_profissional_numero'),
        ('servicos', '0004_alter_servico_servicossolicitados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='servicosFeitos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional_servicos', to='profissionais.profissional'),
        ),
    ]
