# Generated by Django 5.1.7 on 2025-03-14 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_alter_profissional_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
    ]
