# Generated by Django 5.1.7 on 2025-03-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0005_alter_profissional_cpf_alter_profissional_user_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='dataNascimento',
            field=models.DateField(default='2023-03-03'),
        ),
    ]
