# Generated by Django 5.1.7 on 2025-03-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0013_alter_profissional_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='updated_at',
        ),
    ]
