# Generated by Django 5.1.7 on 2025-04-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0014_remove_profissional_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='numero',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
