# Generated by Django 5.1.7 on 2025-04-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0015_profissional_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='numero',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
