# Generated by Django 5.1.7 on 2025-04-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0017_profissional_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='imagem',
            field=models.ImageField(upload_to='midia/'),
        ),
    ]
