# Generated by Django 5.1.7 on 2025-04-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0021_alter_profissional_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='foto_perfil',
            field=models.ImageField(upload_to='profissionais'),
        ),
    ]
