# Generated by Django 5.1.7 on 2025-05-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0023_alter_profissional_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='numero',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
