# Generated by Django 5.1.7 on 2025-03-08 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dataNascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('dataInicio', models.DateField()),
                ('idProfissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to='profissionais.profissao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
