# Generated by Django 5.1.7 on 2025-03-14 22:22

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='profissional',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='dataNascimento',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='nome',
        ),
        migrations.AddField(
            model_name='profissional',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
