# Generated by Django 5.1.7 on 2025-03-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0007_profissao_created_at_profissao_deleted_at_and_more'),
    ]

    operations = [
    ]
