# Generated by Django 5.1.7 on 2025-03-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0008_install_trigram'),
    ]

    operations = [
    ]
