# Generated by Django 5.1.7 on 2025-03-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0009_install_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='cepp',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='nivel_profissional',
            field=models.CharField(choices=[('I', 'Iniciante'), ('Q', 'Qualificado'), ('P', 'Profissional')], default='I', max_length=50),
        ),
    ]
