# Generated by Django 5.1.7 on 2025-03-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0010_profissional_nivel_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='nivel_profissional',
            field=models.CharField(choices=[('I', 'Iniciante'), ('Q', 'Qualificado'), ('P', 'Profissional,')], default='I', max_length=50),
        ),
    ]
