# Generated by Django 5.1.7 on 2025-03-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0010_profissional_cepp_profissional_cidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='cepp',
            new_name='cep',
        ),
    ]
