# Generated by Django 5.1.7 on 2025-03-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0011_alter_profissional_nivel_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='cidade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profissional',
            name='estado',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
