# Generated by Django 5.1.7 on 2025-03-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0012_profissional_cidade_profissional_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
