# Generated by Django 5.1.7 on 2025-03-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0013_alter_profissional_cidade_alter_profissional_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='estado',
        ),
        migrations.AddField(
            model_name='profissional',
            name='cep',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
