# Generated by Django 5.1.7 on 2025-03-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0014_remove_profissional_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profissional',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
