# Generated by Django 5.1.7 on 2025-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0016_alter_profissional_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='imagem',
            field=models.ImageField(default=1, upload_to='midia/profissionais'),
            preserve_default=False,
        ),
    ]
