# Generated by Django 5.1.7 on 2025-04-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0018_alter_profissional_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='imagem',
        ),
        migrations.AddField(
            model_name='profissional',
            name='foto_perfil',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
