# Generated by Django 5.1.7 on 2025-04-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0022_alter_profissional_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profissionais/'),
        ),
    ]
