# Generated by Django 5.1.7 on 2025-03-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_cpf_cliente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dataNascimento',
            field=models.DateField(default='2023-03-03'),
        ),
    ]
