# Generated by Django 5.1.7 on 2025-03-17 23:55

from django.db import migrations


class Migration(migrations.Migration):
    
    def corrigir_cliente_id(apps, schema_editor):
    # Corrige os dados existentes, se possível
        if schema_editor.connection.vendor == 'postgresql':
            schema_editor.execute(
                """
                ALTER TABLE clientes_endereco
                ALTER COLUMN cliente_id TYPE integer USING (cliente_id::integer);
                """
            )

    dependencies = [
        ('clientes', '0012_alter_endereco_cliente'),
    ]

    operations = [
        migrations.RunPython(corrigir_cliente_id, reverse_code=migrations.RunPython.noop),
    ]
