# Generated by Django 5.1.7 on 2025-03-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_cliente_email_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email_profissional',
        ),
    ]
