# Generated by Django 5.1.7 on 2025-03-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='idProfissional',
            new_name='servicosFeitos',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='idCliente',
            new_name='servicosSolicitados',
        ),
    ]
