# Generated by Django 5.1.7 on 2025-04-02 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_alter_cliente_numero'),
        ('servicos', '0003_servico_created_at_servico_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='servicosSolicitados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_servicos', to='clientes.cliente'),
        ),
    ]
