# Generated by Django 5.1.7 on 2025-03-08 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('conteudo', models.ImageField(upload_to='')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('idServico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('Post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.postservico')),
            ],
        ),
    ]
