# Generated by Django 5.1.7 on 2025-03-17 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postservico_conteudo'),
        ('profissionais', '0009_install_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='postservico',
            name='profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postservico',
            name='conteudo',
            field=models.ImageField(blank=True, null=True, upload_to='imagem/'),
        ),
    ]
