# Generated by Django 5.1.7 on 2025-03-24 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postservico_profissional_alter_postservico_conteudo'),
        ('servicos', '0003_servico_created_at_servico_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopost',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postservico'),
        ),
        migrations.AlterField(
            model_name='postservico',
            name='idServico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico'),
        ),
    ]
