# Generated by Django 5.1.7 on 2025-04-02 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comentariopost_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariopost',
            name='curtidas',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='postservico',
            name='curtidas',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comentariopost',
            name='Post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.postservico'),
        ),
    ]
