# Generated by Django 5.1.7 on 2025-04-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comentariopost_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservico',
            name='dataCriacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
