# Generated by Django 5.1.7 on 2025-04-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_comentariopost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopost',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postservico'),
        ),
    ]
