# Generated by Django 5.1.7 on 2025-04-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_comentariopost_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postservico',
            name='titulo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
