# Generated by Django 5.1.7 on 2025-05-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_rename_curtidas_postservico_curtida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curtida',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='curtida',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='curtida',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='curtida',
            name='updated_at',
        ),
    ]
