# Generated by Django 5.1.7 on 2025-05-13 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_remove_curtida_created_at_remove_curtida_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopost',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.postservico'),
        ),
    ]
