# Generated by Django 5.1.7 on 2025-05-13 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_alter_comentariopost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariopost',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='posts.postservico'),
        ),
    ]
