# Generated by Django 5.1.7 on 2025-03-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_options_remove_cliente_is_deleted_and_more'),
    ]

    operations = [
    ]
