# Generated by Django 5.1.7 on 2025-03-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_endereco_cidade_alter_endereco_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='updated_at',
        ),
    ]
