# Generated by Django 5.1.7 on 2025-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_remove_cliente_created_at_remove_cliente_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_profissional',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
