# Generated by Django 5.1.7 on 2025-04-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_remove_cliente_email_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
