# Generated by Django 5.1.7 on 2025-05-13 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_alter_cliente_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='biografia',
        ),
    ]
