# Generated by Django 5.1.7 on 2025-05-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_alter_cliente_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
