# Generated by Django 5.1.7 on 2025-05-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_alter_cliente_numero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
